import React from 'react';

const ShowcaseSection = () => {
  return (
    <><section className="mostra-section" id="mostraSection" data-header="claro">
        <div className="mostra-grade">

            <header className="mostra-topo">
                <h2 className="mostra-headline">Se você sabe mandar uma mensagem no WhatsApp, já sabe usar o Simplific Pro.</h2>
                
                <p className="mostra-sub">Fale com a IA do mesmo jeito que fala com um amigo. Peça com as palavras que vierem à cabeça, por texto ou áudio. Ela entende o que você precisa.</p>
            </header>
        </div>


        <div className="mostra-esteiras">

            <div className="mostra-trilho">
                <div className="mostra-fita mostra-f1">
                    <div className="mostra-fila">
                        <span className="mostra-bolha"><span className="mostra-txt">bom dia! o que eu tenho hoje?</span><span className="mostra-meta">07:04<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">gastei 62 na farmácia agora</span><span className="mostra-meta">09:12<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">minha fatura já fechou?</span><span className="mostra-meta">23:05<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">cria o link do meet da call de amanhã</span><span className="mostra-meta">17:35<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">cobra o Vitor todo dia 10 🙏</span><span className="mostra-meta">17:41<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">guarda essa aqui</span><span className="mostra-meta">13:58<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Quantas tarefas fechei essa semana?</span><span className="mostra-meta">20:08<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">adiciona a minha esposa na conta ❤️</span><span className="mostra-meta">20:33<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">puxa minha semana do google agenda</span><span className="mostra-meta">08:41<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Almoço R$ 141,60 no cartão do Itaú.</span><span className="mostra-meta">13:47<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Quanto foi de mercado em agosto?</span><span className="mostra-meta">21:04<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">reunião semanal toda terça 9h</span><span className="mostra-meta">09:09<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">lembra meu irmão do aniversário da mãe dia 27</span><span className="mostra-meta">18:09<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">vc acha o comprovante do aluguel?</span><span className="mostra-meta">15:22<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">anota a ideia da assinatura anual</span><span className="mostra-meta">23:17<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                    </div>
                    
                    <div className="mostra-fila" aria-hidden="true">
                        <span className="mostra-bolha"><span className="mostra-txt">bom dia! o que eu tenho hoje?</span><span className="mostra-meta">07:04<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">gastei 62 na farmácia agora</span><span className="mostra-meta">09:12<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">minha fatura já fechou?</span><span className="mostra-meta">23:05<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">cria o link do meet da call de amanhã</span><span className="mostra-meta">17:35<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">cobra o Vitor todo dia 10 🙏</span><span className="mostra-meta">17:41<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">guarda essa aqui</span><span className="mostra-meta">13:58<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Quantas tarefas fechei essa semana?</span><span className="mostra-meta">20:08<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">adiciona a minha esposa na conta ❤️</span><span className="mostra-meta">20:33<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">puxa minha semana do google agenda</span><span className="mostra-meta">08:41<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Almoço R$ 141,60 no cartão do Itaú.</span><span className="mostra-meta">13:47<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Quanto foi de mercado em agosto?</span><span className="mostra-meta">21:04<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">reunião semanal toda terça 9h</span><span className="mostra-meta">09:09<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">lembra meu irmão do aniversário da mãe dia 27</span><span className="mostra-meta">18:09<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">vc acha o comprovante do aluguel?</span><span className="mostra-meta">15:22<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">anota a ideia da assinatura anual</span><span className="mostra-meta">23:17<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                    </div>
                </div>
            </div>

            <div className="mostra-trilho">
                <div className="mostra-fita mostra-f2">
                    <div className="mostra-fila">
                        <span className="mostra-bolha"><span className="mostra-txt">Uber 23,90, débito.</span><span className="mostra-meta">22:51<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Marca meu almoço com a Cláudia sexta.</span><span className="mostra-meta">10:05<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">me avisa antes do alvará vencer</span><span className="mostra-meta">10:27<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Me avisa antes de vencer a fatura do cartão.</span><span className="mostra-meta">08:55<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Cria a tarefa de revisar o contrato.</span><span className="mostra-meta">11:55<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Preciso de um link de cobrança de R$ 1.280.</span><span className="mostra-meta">10:52<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Marca uma reunião com o time quinta 14h30.</span><span className="mostra-meta">08:47<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Quero que o meu sócio veja só os gastos.</span><span className="mostra-meta">16:42<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Me manda tudo o que tem da reforma.</span><span className="mostra-meta">19:14<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">me lembra do remedio todo dia 20h</span><span className="mostra-meta">19:58<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">vou te mandar a foto da nota do posto</span><span className="mostra-meta">15:44<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">no crédito, quanto já foi esse mês?</span><span className="mostra-meta">12:44<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">me manda a ata da reunião de ontem</span><span className="mostra-meta">10:47<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">lembra os alunos da mensalidade dia 5</span><span className="mostra-meta">08:33<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">o que ta atrasado no projeto do site?</span><span className="mostra-meta">17:29<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                    </div>
                    
                    <div className="mostra-fila" aria-hidden="true">
                        <span className="mostra-bolha"><span className="mostra-txt">Uber 23,90, débito.</span><span className="mostra-meta">22:51<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Marca meu almoço com a Cláudia sexta.</span><span className="mostra-meta">10:05<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">me avisa antes do alvará vencer</span><span className="mostra-meta">10:27<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Me avisa antes de vencer a fatura do cartão.</span><span className="mostra-meta">08:55<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Cria a tarefa de revisar o contrato.</span><span className="mostra-meta">11:55<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Preciso de um link de cobrança de R$ 1.280.</span><span className="mostra-meta">10:52<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Marca uma reunião com o time quinta 14h30.</span><span className="mostra-meta">08:47<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Quero que o meu sócio veja só os gastos.</span><span className="mostra-meta">16:42<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Me manda tudo o que tem da reforma.</span><span className="mostra-meta">19:14<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">me lembra do remedio todo dia 20h</span><span className="mostra-meta">19:58<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">vou te mandar a foto da nota do posto</span><span className="mostra-meta">15:44<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">no crédito, quanto já foi esse mês?</span><span className="mostra-meta">12:44<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">me manda a ata da reunião de ontem</span><span className="mostra-meta">10:47<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">lembra os alunos da mensalidade dia 5</span><span className="mostra-meta">08:33<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">o que ta atrasado no projeto do site?</span><span className="mostra-meta">17:29<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                    </div>
                </div>
            </div>

            <div className="mostra-trilho">
                <div className="mostra-fita mostra-f3">
                    <div className="mostra-fila">
                        <span className="mostra-bolha"><span className="mostra-txt">quanto sobrou pra fechar o mes? 😬</span><span className="mostra-meta">21:36<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">acha o documento do carro, o CRLV</span><span className="mostra-meta">16:58<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">poe o dentista no meu google agenda</span><span className="mostra-meta">15:02<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">reenvia o link de cobrança pra Renata</span><span className="mostra-meta">18:47<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Paguei 1.240,00 de aluguel hoje.</span><span className="mostra-meta">13:31<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">chama o Douglas e a Bia pra sexta 16h</span><span className="mostra-meta">16:26<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">novo projeto: mudança do escritório</span><span className="mostra-meta">10:03<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Theo, quem tem acesso à conta?</span><span className="mostra-meta">11:06<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Compara meu gasto com o do mês passado.</span><span className="mostra-meta">09:44<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Sofi, me manda o resumo do dia todo dia às 7h.</span><span className="mostra-meta">07:22<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Preciso da nota fiscal do notebook.</span><span className="mostra-meta">11:19<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">toda segunda tem 89,90 da academia</span><span className="mostra-meta">07:38<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">me lembra de pagar o INSS dia 20</span><span className="mostra-meta">11:28<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">a reunião de sexta pode virar 15h?</span><span className="mostra-meta">14:12<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">nao me deixa esquecer de ligar pro contador</span><span className="mostra-meta">18:26<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                    </div>
                    
                    <div className="mostra-fila" aria-hidden="true">
                        <span className="mostra-bolha"><span className="mostra-txt">quanto sobrou pra fechar o mes? 😬</span><span className="mostra-meta">21:36<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">acha o documento do carro, o CRLV</span><span className="mostra-meta">16:58<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">poe o dentista no meu google agenda</span><span className="mostra-meta">15:02<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">reenvia o link de cobrança pra Renata</span><span className="mostra-meta">18:47<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Paguei 1.240,00 de aluguel hoje.</span><span className="mostra-meta">13:31<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">chama o Douglas e a Bia pra sexta 16h</span><span className="mostra-meta">16:26<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">novo projeto: mudança do escritório</span><span className="mostra-meta">10:03<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Theo, quem tem acesso à conta?</span><span className="mostra-meta">11:06<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Compara meu gasto com o do mês passado.</span><span className="mostra-meta">09:44<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Sofi, me manda o resumo do dia todo dia às 7h.</span><span className="mostra-meta">07:22<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">Preciso da nota fiscal do notebook.</span><span className="mostra-meta">11:19<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">toda segunda tem 89,90 da academia</span><span className="mostra-meta">07:38<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">me lembra de pagar o INSS dia 20</span><span className="mostra-meta">11:28<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">a reunião de sexta pode virar 15h?</span><span className="mostra-meta">14:12<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                        <span className="mostra-bolha"><span className="mostra-txt">nao me deixa esquecer de ligar pro contador</span><span className="mostra-meta">18:26<svg className="mostra-visto" viewBox="0 0 17 11" aria-hidden="true"><path d="M1.2 6.4 4.1 9.2 9.9 2.1"/><path d="M7.4 9.2 13.2 2.1"/></svg></span></span>
                    </div>
                </div>
            </div>
        </div>

        <a className="hero-btn mostra-btn" href="/como-usar"><span>Veja o que dá para pedir</span></a>
    </section></>
  );
};

export default ShowcaseSection;
