"""Adiciona preferencia de formato de resposta para usuario

Revision ID: 2e7eb276304f
Revises: 90cbf8750801
Create Date: 2025-08-13 09:46:04.994946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7eb276304f'
down_revision = '90cbf8750801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_response_format', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_response_format')

    # ### end Alembic commands ###
