"""add secondary user fields

Revision ID: 37eade036426
Revises: 5ca18c3dfcfd
Create Date: 2026-01-30 19:15:42.684438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37eade036426'
down_revision = '5ca18c3dfcfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('secondary_whatsapp', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(None, ['secondary_whatsapp'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secondary_whatsapp')
        batch_op.drop_column('secondary_name')

    # ### end Alembic commands ###
