"""Adiciona campos Google Calendar

Revision ID: 386086518345
Revises: 565cd61608e4
Create Date: 2025-11-27 22:30:07.260635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386086518345'
down_revision = '565cd61608e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_event_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_refresh_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_refresh_token')
        batch_op.drop_column('google_calendar_token')

    with op.batch_alter_table('schedule_events', schema=None) as batch_op:
        batch_op.drop_column('google_event_id')

    # ### end Alembic commands ###
