"""Adiciona campo de validade da assinatura ao Usuario

Revision ID: 40de220f6db2
Revises: da669217ee80
Create Date: 2025-09-14 12:46:42.596825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40de220f6db2'
down_revision = 'da669217ee80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_valid_until', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_valid_until')

    # ### end Alembic commands ###
