"""Adiciona contas a pagar

Revision ID: 42f84dfd738a
Revises: fb0b193dcbab
Create Date: 2026-02-03 11:29:30.854189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f84dfd738a'
down_revision = 'fb0b193dcbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_payables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('due_date', sa.String(length=10), nullable=False),
    sa.Column('extension_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('nf_type', sa.String(length=50), nullable=True),
    sa.Column('doc_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['business_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['business_categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['business_companies.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['business_stakeholders.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['business_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_payables')
    # ### end Alembic commands ###
