"""Reestrutura orcamento clean

Revision ID: 510a9db5b59c
Revises: c729bf74e44f
Create Date: 2026-02-02 22:29:19.554306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510a9db5b59c'
down_revision = 'c729bf74e44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('period_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['business_companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('base_value', sa.Float(), nullable=True),
    sa.Column('is_replicated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['business_budgets.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['business_categories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['business_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('month_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['business_budget_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_budget_items')
    op.drop_table('business_budget_lines')
    op.drop_table('business_budgets')
    # ### end Alembic commands ###
