"""Consolidando modelos business

Revision ID: 564848bc8b51
Revises: 14ebd9aea8f7
Create Date: 2026-02-02 18:14:43.645309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564848bc8b51'
down_revision = '14ebd9aea8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('cnae', sa.String(length=20), nullable=True),
    sa.Column('data_abertura', sa.String(length=20), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=True),
    sa.Column('representante', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_companies')
    # ### end Alembic commands ###
