"""Adiciona receipt_image_url na Transaction

Revision ID: 565cd61608e4
Revises: 434c389214e1
Create Date: 2025-11-17 22:20:41.789147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565cd61608e4'
down_revision = '434c389214e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('receipt_image_url')

    # ### end Alembic commands ###
