"""Adiciona campos Pluggy

Revision ID: 5848a2dfe9d3
Revises: 386086518345
Create Date: 2025-12-14 19:33:45.443149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5848a2dfe9d3'
down_revision = '386086518345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pluggy_transaction_id', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['pluggy_transaction_id'])

    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pluggy_item_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pluggy_credit_card_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_column('pluggy_credit_card_id')
        batch_op.drop_column('pluggy_item_id')

    with op.batch_alter_table('credit_card_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pluggy_transaction_id')

    # ### end Alembic commands ###
