"""Adiciona campos bank

Revision ID: 88c16eb5be85
Revises: e5851197b750
Create Date: 2026-02-06 22:12:25.078669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c16eb5be85'
down_revision = 'e5851197b750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bank_accounts', ['bank_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bank_account_id')

    # ### end Alembic commands ###
