"""Adiciona vinculo entre transacao e planejamento

Revision ID: ab6e71044698
Revises: 2e7eb276304f
Create Date: 2025-08-26 18:05:48.158397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6e71044698'
down_revision = '2e7eb276304f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planning_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planning', ['planning_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planning_id')

    # ### end Alembic commands ###
