"""Add name column to users table

Revision ID: b202af8ed4fb
Revises: de59128aa516
Create Date: 2025-08-06 17:28:27.812989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b202af8ed4fb'
down_revision = 'de59128aa516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_items')
    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.alter_column('cartao_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('valor_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('mes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ano',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'em_aberto'::character varying"))
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('valor')
        batch_op.drop_column('numero_usuario')
        batch_op.drop_column('cartao_ultimos_quatro')
        batch_op.drop_column('cartao_nome')
        batch_op.drop_column('descricao')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    with op.batch_alter_table('schedule_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))

    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cartao_nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cartao_ultimos_quatro', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numero_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('valor', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_criacao', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'em_aberto'::character varying"))
        batch_op.alter_column('ano',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('valor_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cartao_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('schedule_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recurring_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('schedule_items_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('schedule_items_pkey'))
    )
    # ### end Alembic commands ###
