"""Adiciona campo de foto de perfil ao usuario

Revision ID: cb6b9f4e0824
Revises: ffa7b147f26d
Create Date: 2025-09-18 17:15:30.584805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6b9f4e0824'
down_revision = 'ffa7b147f26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image_url')

    # ### end Alembic commands ###
