"""Adiciona opcao de resumo semanal para usuario

Revision ID: da669217ee80
Revises: ab6e71044698
Create Date: 2025-08-28 11:50:01.833275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da669217ee80'
down_revision = 'ab6e71044698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receive_weekly_summary', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('receive_weekly_summary')

    # ### end Alembic commands ###
