import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Button } from '@/components/ui/button';
import {
  ArrowRight, BellRing, Brain, CalendarDays, Check, ChevronDown, ChevronUp,
  CircleDollarSign, CreditCard, FileText, FolderOpen, KeyRound, LockKeyhole,
  MessageCircle, Mic, Network, Search, ShieldCheck, Sparkles, Target, TrendingUp,
  WalletCards,
} from 'lucide-react';

const moments = [
  { time: '07:40', title: 'O aviso da fatura chega antes do café.', text: 'O Simplific acompanha suas contas e lembra você dos próximos vencimentos antes que eles virem preocupação.', icon: BellRing, card: 'Fatura Nubank vence em 3 dias', tone: 'bg-lime-300 text-[#10130d]' },
  { time: '09:15', title: 'Um áudio no caminho e a consulta entra na agenda.', text: 'Fale naturalmente. A agenda entende data, horário e lembrete a partir de uma simples mensagem.', icon: CalendarDays, card: 'Consulta · quinta-feira, 15:30', tone: 'bg-[#b5a6ff] text-[#17132a]' },
  { time: '12:30', title: 'Pagou o almoço? Já está registrado.', text: 'Com seus dados conectados, o Simplific organiza movimentações e categoriza seus gastos automaticamente.', icon: WalletCards, card: 'Alimentação · R$ 42,00', tone: 'bg-[#ffcc87] text-[#2b1c09]' },
  { time: '15:30', title: 'Não encontra um documento? É só mandar uma mensagem.', text: 'Comprovantes e arquivos ficam organizados para você buscar pelo WhatsApp sempre que precisar.', icon: FolderOpen, card: 'Comprovante de aluguel · encontrado', tone: 'bg-[#9fd7ff] text-[#0c2030]' },
  { time: '22:00', title: 'Antes de dormir, o resumo do dia já está pronto.', text: 'O Simplific reúne o que aconteceu, o que vem pela frente e as prioridades de amanhã.', icon: Sparkles, card: '4 tarefas resolvidas hoje', tone: 'bg-[#f6a6bd] text-[#32121f]' },
];

const advisors = [
  { name: 'Nexo', role: 'Assessor financeiro', image: '/assets/landing/simplific-assessor-financeiro.jpg', text: 'Organiza gastos, acompanha cartões e mostra os padrões do seu dinheiro.' },
  { name: 'Clara', role: 'Assessora executiva', image: '/assets/landing/simplific-assessor-agenda.jpg', text: 'Cuida de lembretes, compromissos e prioridades sem você abrir outro app.' },
  { name: 'Atlas', role: 'Assessor de documentos', image: '/assets/landing/simplific-assessor-documentos.jpg', text: 'Encontra comprovantes, lê documentos e deixa tudo acessível quando você precisa.' },
];

const features = [
  { icon: MessageCircle, title: 'Conversa que entende você', text: 'Pergunte, mande áudio ou envie uma foto. O Simplific entende sua intenção e resolve sem formulários.' },
  { icon: Network, title: 'Tudo conectado', text: 'Contas, cartões, agenda, documentos e metas em uma visão organizada para sua rotina.' },
  { icon: TrendingUp, title: 'Clareza para decidir', text: 'Padrões, alertas e insights para você saber onde está e qual é o próximo passo.' },
];

const faqs = [
  ['O Simplific é seguro?', 'Sim. Seus dados são protegidos, a conexão é feita com segurança e o Simplific não movimenta seu dinheiro.'],
  ['Preciso instalar algum aplicativo?', 'Você pode começar pelo WhatsApp. O painel web complementa a experiência para análises e acompanhamento.'],
  ['Como eu peço as coisas?', 'É só mandar uma mensagem ou áudio, do seu jeito. Você pode pedir para registrar gastos, criar lembretes, consultar informações e muito mais.'],
  ['Posso usar com minha família ou sócios?', 'Sim. O Simplific pode apoiar a organização de uma rotina compartilhada, conforme o plano e as configurações da sua conta.'],
  ['Posso cancelar quando quiser?', 'Sim. Você pode cancelar pelo painel sem burocracia ou taxas surpresa.'],
];

function FaqItem({ question, answer }) {
  const [open, setOpen] = useState(false);
  return <div className="border-b border-white/10"><button type="button" onClick={() => setOpen(!open)} className="flex w-full items-center justify-between gap-6 py-6 text-left text-base font-medium text-white hover:text-lime-300 md:text-lg"><span>{question}</span>{open ? <ChevronUp size={20} className="shrink-0 text-lime-300" /> : <ChevronDown size={20} className="shrink-0 text-white/40" />}</button>{open && <p className="max-w-2xl pb-6 pr-8 text-sm leading-7 text-white/50">{answer}</p>}</div>;
}

function FloatingPhone() {
  return <div className="relative mx-auto w-full max-w-4xl"><div className="absolute -inset-8 rounded-[42px] bg-lime-300/[.07] blur-3xl" /><div className="relative overflow-hidden rounded-[32px] border border-white/10 bg-[#050605] shadow-[0_30px_100px_rgba(0,0,0,.55)]"><img src="/assets/landing/simplific-hero-hands.jpg" alt="Demonstração do Simplific com conexão humana e digital" className="block aspect-[16/9] w-full object-cover" /><div className="absolute bottom-5 left-5 right-5 flex items-center justify-between rounded-2xl border border-white/15 bg-[#090a09]/80 px-4 py-3 text-xs text-white/70 backdrop-blur-xl"><span className="flex items-center gap-2"><Sparkles size={14} className="text-lime-300" /> Seu dia, organizado em uma conversa</span><ArrowRight size={15} className="text-lime-300" /></div></div><div className="absolute -left-4 top-10 hidden rounded-2xl border border-white/10 bg-[#141714]/95 p-3 shadow-2xl sm:block"><div className="flex items-center gap-2 text-xs text-white/65"><CircleDollarSign size={15} className="text-lime-300" /> Delivery · R$ 42,00</div><div className="mt-2 text-[10px] text-white/35">Registrado automaticamente</div></div><div className="absolute -right-4 bottom-14 hidden rounded-2xl border border-white/10 bg-[#141714]/95 p-3 shadow-2xl sm:block"><div className="text-[10px] text-white/40">Insights desta semana</div><div className="mt-1 flex items-center gap-2 text-sm font-semibold text-white"><TrendingUp size={15} className="text-lime-300" /> 12,4% melhor</div></div></div>;
}

const HomePage = () => {
  const navigate = useNavigate();
  const [activeMoment, setActiveMoment] = useState(0);
  const [billingCycle, setBillingCycle] = useState('annual');

  useEffect(() => {
    const script = document.createElement('script');
    script.src = 'https://s3.amazonaws.com/raichu-beta/ra-verified/bundle.js';
    script.async = true;
    script.id = 'ra-embed-verified-seal';
    script.setAttribute('data-id', 'UWJISTEzOXlvV09HWFhuOTo0MS04NTEtMDI5LWZlbGlwZS12aWFuYS1kZS1vbGl2ZWlyYQ==');
    script.setAttribute('data-target', 'ra-verified-seal');
    script.setAttribute('data-model', 'compact_3');
    document.body.appendChild(script);
    return () => document.getElementById('ra-embed-verified-seal')?.remove();
  }, []);

  const plan = billingCycle === 'annual'
    ? { old: 'R$ 358,80', price: '16,58', detail: 'No plano anual. Ou R$ 199,00 à vista', badge: 'Melhor escolha · 45% OFF', button: 'Garantir oferta anual' }
    : { old: null, price: '29,90', detail: 'Sem fidelidade. Cancele quando quiser.', badge: 'Flexibilidade total', button: 'Assinar mensal' };

  const handleBuyClick = () => {
    if (window.fbq) window.fbq('track', 'InitiateCheckout', { content_name: billingCycle === 'monthly' ? 'Plano Mensal' : 'Plano Anual', value: billingCycle === 'monthly' ? 29.9 : 199, currency: 'BRL' });
    navigate(billingCycle === 'monthly' ? '/checkout' : '/checkout?plan=annual');
  };

  const current = moments[activeMoment];
  const CurrentIcon = current.icon;

  return <div className="simplific-landing min-h-screen overflow-x-hidden bg-[#080908] font-sans text-white selection:bg-lime-300 selection:text-black">
    <Navbar />
    <main>
      <section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(192,255,72,.10),transparent_34%),radial-gradient(circle_at_50%_70%,rgba(192,255,72,.05),transparent_35%)]" /><div className="container relative mx-auto max-w-7xl px-5 pb-20 pt-20 text-center md:px-10 md:pb-28 md:pt-28"><div className="mx-auto max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-xs text-white/60"><span className="h-1.5 w-1.5 rounded-full bg-lime-300" /> Assistente financeiro e pessoal com IA</span><h1 className="mt-7 text-5xl font-semibold leading-[.98] tracking-[-.06em] md:text-7xl">Sua vida organizada começa numa <span className="text-lime-300">conversa.</span></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-white/50 md:text-lg">Uma equipe de assessores no seu WhatsApp cuida do seu dinheiro, da sua agenda e dos seus documentos. Você só manda mensagem.</p><div className="mt-8 flex justify-center"><Button onClick={() => navigate('/planos')} className="h-14 rounded-full bg-lime-300 px-8 text-base font-semibold text-[#10130d] shadow-[0_0_40px_rgba(192,255,72,.16)] hover:bg-lime-200">Começar agora <ArrowRight className="ml-2" size={18} /></Button></div></div><div className="mx-auto mt-16 max-w-5xl"><FloatingPhone /></div><div className="mt-12 flex flex-wrap justify-center gap-x-8 gap-y-3 text-xs text-white/40"><span className="flex items-center gap-2"><ShieldCheck size={14} className="text-lime-300" /> Segurança de nível bancário</span><span className="flex items-center gap-2"><LockKeyhole size={14} className="text-lime-300" /> Só leitura</span><span className="flex items-center gap-2"><Network size={14} className="text-lime-300" /> Open Finance</span></div></div></section>

      <section className="border-b border-white/10 bg-[#0b0c0b] py-8"><div className="container mx-auto grid max-w-5xl grid-cols-2 gap-6 px-5 text-center md:grid-cols-4 md:px-10"><div><strong className="block text-2xl font-semibold">+15 anos</strong><span className="text-xs text-white/40">de experiência</span></div><div><strong className="block text-2xl font-semibold">24h/7</strong><span className="text-xs text-white/40">assistência disponível</span></div><div><strong className="block text-2xl font-semibold">100%</strong><span className="text-xs text-white/40">dados protegidos</span></div><div><strong className="block text-2xl font-semibold">1 lugar</strong><span className="text-xs text-white/40">para sua vida financeira</span></div></div></section>

      <section className="py-24 md:py-32"><div className="container mx-auto max-w-7xl px-5 md:px-10"><div className="mx-auto mb-14 max-w-2xl text-center"><span className="text-xs font-semibold uppercase tracking-[.22em] text-lime-300">Como funciona</span><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Mande uma mensagem. <span className="text-white/45">O resto se organiza.</span></h2><p className="mt-5 text-white/45">Você não precisa aprender uma ferramenta nova. Só conversar com o Simplific.</p></div><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div className="space-y-2">{moments.map((moment, index) => { const Icon = moment.icon; return <button key={moment.time} type="button" onClick={() => setActiveMoment(index)} className={`flex w-full items-start gap-4 rounded-2xl p-4 text-left transition-all ${activeMoment === index ? 'bg-white/[.07] text-white' : 'text-white/40 hover:bg-white/[.03] hover:text-white/70'}`}><span className={`mt-0.5 text-xs font-semibold ${activeMoment === index ? 'text-lime-300' : 'text-white/30'}`}>{moment.time}</span><span className="flex-1"><strong className="block text-sm font-medium leading-6">{moment.title}</strong>{activeMoment === index && <span className="mt-2 block text-xs leading-5 text-white/45">{moment.text}</span>}</span><Icon size={17} className={activeMoment === index ? 'text-lime-300' : 'text-white/25'} /></button>; })}</div><div className="relative min-h-[390px] overflow-hidden rounded-[32px] border border-white/10 bg-[#0d0f0d] p-6 md:p-10"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-lime-300/[.08] blur-3xl" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between"><div><span className="text-xs text-white/35">Agora, no seu Simplific</span><h3 className="mt-2 text-2xl font-medium">{current.title}</h3></div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-lime-300/10 text-lime-300"><CurrentIcon size={23} /></div></div><div className="mx-auto my-10 w-full max-w-md"><div className="rounded-3xl border border-white/10 bg-[#080908] p-5 shadow-2xl"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-lime-300 text-[#10130d]"><CurrentIcon size={19} /></div><div><p className="text-xs text-white/35">Simplific · agora</p><p className="mt-1 text-sm text-white/80">{current.card}</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-2/3 rounded-full bg-lime-300 transition-all duration-300" /></div><p className="mt-3 text-xs leading-5 text-white/40">{current.text}</p></div></div><div className={`ml-auto rounded-2xl px-4 py-3 text-xs font-medium shadow-lg ${current.tone}`}>Resolvido pelo Simplific <Check className="ml-2 inline" size={13} /></div></div></div></div></div></section>

      <section className="border-y border-white/10 bg-[#0b0c0b] py-24 md:py-32"><div className="container mx-auto max-w-7xl px-5 md:px-10"><div className="mx-auto mb-14 max-w-2xl text-center"><span className="text-xs font-semibold uppercase tracking-[.22em] text-lime-300">Sua equipe pessoal</span><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Um assessor especializado em cada parte da sua rotina.</h2><p className="mt-5 text-white/45">Eles trabalham juntos, mas cada um sabe exatamente como deixar seu dia mais leve.</p></div><div className="grid gap-4 md:grid-cols-3">{advisors.map((advisor) => <div key={advisor.name} className="group overflow-hidden rounded-3xl border border-white/10 bg-[#101210]"><img src={advisor.image} alt={advisor.role} className="h-80 w-full object-cover object-top grayscale transition-all duration-500 group-hover:grayscale-0" /><div className="p-6"><span className="text-xs uppercase tracking-[.18em] text-lime-300">{advisor.role}</span><h3 className="mt-2 text-2xl font-medium">{advisor.name}</h3><p className="mt-3 text-sm leading-6 text-white/45">{advisor.text}</p></div></div>)}</div><div className="mt-10 text-center"><Button onClick={() => navigate('/beneficios')} variant="outline" className="rounded-full border-white/15 text-white hover:bg-white/10">Conhecer todos os recursos <ArrowRight className="ml-2" size={17} /></Button></div></div></section>

      <section className="py-24 md:py-32"><div className="container mx-auto max-w-7xl px-5 md:px-10"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr] md:items-center"><div><span className="text-xs font-semibold uppercase tracking-[.22em] text-lime-300">Tudo o que você pode pedir</span><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] md:text-6xl">Do gasto do almoço ao seu próximo objetivo.</h2><p className="mt-6 text-base leading-7 text-white/50">Uma conversa só para organizar o que antes ficava espalhado em planilhas, aplicativos e anotações.</p><Button onClick={() => navigate('/planos')} className="mt-8 rounded-full bg-lime-300 px-6 font-semibold text-[#10130d] hover:bg-lime-200">Contratar minha equipe <ArrowRight className="ml-2" size={17} /></Button></div><div className="grid gap-4 sm:grid-cols-2">{features.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-3xl border border-white/10 bg-white/[.025] p-6 transition-all hover:-translate-y-1 hover:border-lime-300/35"><Icon size={22} className="text-lime-300" /><h3 className="mt-12 text-lg font-medium">{title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{text}</p></div>)}<div className="overflow-hidden rounded-3xl border border-white/10 sm:col-span-2"><img src="/assets/landing/simplific-insight.jpg" alt="Insights financeiros do Simplific" className="h-64 w-full object-cover opacity-80 transition-transform duration-700 hover:scale-105" /></div></div></div></div></section>

      <section className="border-y border-white/10 bg-[#0b0c0b] py-24 md:py-32"><div className="container mx-auto grid max-w-7xl gap-14 px-5 md:grid-cols-[1.1fr_.9fr] md:items-center md:px-10"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-[#090a09] p-6"><LockKeyhole className="text-lime-300" size={24} /><h3 className="mt-12 text-lg font-medium">Só leitura, zero transações</h3><p className="mt-3 text-sm leading-6 text-white/45">O Simplific não pode fazer transferências ou pagamentos.</p></div><div className="rounded-3xl border border-white/10 bg-[#090a09] p-6"><ShieldCheck className="text-lime-300" size={24} /><h3 className="mt-12 text-lg font-medium">Criptografia bancária</h3><p className="mt-3 text-sm leading-6 text-white/45">Seus dados são protegidos com tecnologia de nível bancário.</p></div><div className="rounded-3xl border border-white/10 bg-[#090a09] p-6"><KeyRound className="text-lime-300" size={24} /><h3 className="mt-12 text-lg font-medium">Sua senha é só sua</h3><p className="mt-3 text-sm leading-6 text-white/45">A conexão acontece no ambiente do seu banco.</p></div><div className="rounded-3xl border border-white/10 bg-[#090a09] p-6"><FileText className="text-lime-300" size={24} /><h3 className="mt-12 text-lg font-medium">LGPD e Open Finance</h3><p className="mt-3 text-sm leading-6 text-white/45">Transparência e controle sobre o que você conecta.</p></div></div><div><span className="text-xs font-semibold uppercase tracking-[.22em] text-lime-300">Segurança primeiro</span><h2 className="mt-4 text-4xl font-semibold leading-tight tracking-[-.04em] md:text-6xl">O Simplific nunca mexe <span className="text-white/45">no seu dinheiro.</span></h2><p className="mt-6 text-base leading-7 text-white/50">Ele só lê. Tipo extrato, só que inteligente. Você continua no controle.</p><Button onClick={() => navigate('/seguranca')} variant="outline" className="mt-8 rounded-full border-white/15 text-white hover:bg-white/10">Conhecer nossa segurança <ArrowRight className="ml-2" size={17} /></Button></div></div></section>

      <section id="oferta" className="py-24 md:py-32"><div className="container mx-auto max-w-4xl px-5 md:px-10"><div className="mb-12 text-center"><span className="text-xs font-semibold uppercase tracking-[.22em] text-lime-300">Planos simples</span><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Comece sem complicação.</h2><p className="mx-auto mt-5 max-w-xl text-white/45">Sua equipe pessoal começa com um clique.</p></div><div className="mx-auto mb-8 flex w-fit rounded-full border border-white/10 bg-white/[.03] p-1"><button type="button" onClick={() => setBillingCycle('monthly')} className={`rounded-full px-5 py-2 text-sm ${billingCycle === 'monthly' ? 'bg-white text-black' : 'text-white/50'}`}>Mensal</button><button type="button" onClick={() => setBillingCycle('annual')} className={`rounded-full px-5 py-2 text-sm ${billingCycle === 'annual' ? 'bg-lime-300 font-semibold text-black' : 'text-white/50'}`}>Anual <span className="ml-1 text-[10px]">-45%</span></button></div><div className="relative overflow-hidden rounded-[32px] border border-lime-300/25 bg-[linear-gradient(120deg,rgba(192,255,72,.10),rgba(255,255,255,.02)_45%)] p-7 md:p-10"><div className="relative flex flex-col justify-between gap-10 md:flex-row md:items-end"><div><span className="inline-flex rounded-full bg-lime-300/15 px-3 py-1 text-xs font-medium text-lime-200">{plan.badge}</span>{plan.old && <p className="mt-8 text-sm text-white/35 line-through">{plan.old}</p>}<div className="mt-1 flex items-end gap-2"><span className="mb-2 text-sm text-white/50">R$</span><strong className="text-6xl font-semibold tracking-[-.06em]">{plan.price}</strong><span className="mb-2 text-white/45">/mês</span></div><p className="mt-4 border-l-2 border-lime-300 pl-3 text-sm text-white/65">{plan.detail}</p><div className="mt-5 flex flex-wrap gap-4 text-xs text-white/45"><span className="flex items-center gap-1.5"><Check size={14} className="text-lime-300" /> Acesso imediato</span><span className="flex items-center gap-1.5"><Check size={14} className="text-lime-300" /> Compra segura</span></div></div><div className="w-full md:w-auto"><Button onClick={handleBuyClick} className="h-14 w-full rounded-full bg-lime-300 px-8 font-semibold text-[#10130d] hover:bg-lime-200 md:w-auto">{plan.button} <ArrowRight className="ml-2" size={17} /></Button><p className="mt-3 text-center text-xs text-white/30">Pagamento seguro via Asaas</p></div></div></div></div></section>

      <section className="border-t border-white/10 bg-[#0b0c0b] py-24"><div className="container mx-auto max-w-3xl px-5 md:px-10"><div className="mb-10 text-center"><span className="text-xs font-semibold uppercase tracking-[.22em] text-lime-300">Perguntas frequentes</span><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em]">Ainda ficou alguma dúvida?</h2></div>{faqs.map(([question, answer]) => <FaqItem key={question} question={question} answer={answer} />)}</div></section>

      <section className="relative overflow-hidden py-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_100%,rgba(192,255,72,.14),transparent_48%)]" /><div className="relative mx-auto max-w-3xl px-5 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-lime-300 text-[#10130d]"><Sparkles size={26} /></div><h2 className="mt-7 text-4xl font-semibold tracking-[-.04em] md:text-6xl">Seu dia organizado antes de você pedir.</h2><p className="mx-auto mt-5 max-w-xl text-white/45">Mais clareza para cuidar do que realmente importa.</p><Button onClick={() => navigate('/planos')} className="mt-8 h-14 rounded-full bg-lime-300 px-8 font-semibold text-[#10130d] hover:bg-lime-200">Começar agora <ArrowRight className="ml-2" size={18} /></Button></div></section>
    </main>
    <Footer />
  </div>;
};

export default HomePage;
